config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password, controller: "clearance/passwords", only: [:edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  post "/block_source", to: "users#block_source", as: "block_source"
  post "/unblock_source", to: "users#unblock_source", as: "unblock_source"
  post "/update_blocked_sources", to: "users#update_blocked_sources", as: "update_blocked_sources"

  get 'data', to: 'data#index'
  root 'pages#index'
end

app/views/pages/index.html.erb
<head>
  <%= stylesheet_link_tag 'application' %>
</head>

<!--FUNCTION FOR RESIZING IMAGES -->
<script>
  function adjustImageSize(image, size) {
    if (image.style.width === size) {
      image.style.width = ""; // Revert to original size
      image.style.height = ""; // Revert to original size
    } else {
      image.style.width = size;
      image.style.height = "auto"; // Adjust height proportionately
    }
  }
</script>

<!-- LOGGED IN / SIGN IN / SIGN UP / BLOCKED SOURCES SECTION -->
<% if signed_in? %>
  <p>Logged in as: <%= current_user.email %></p>
  <%= button_to "Sign Out", sign_out_path, method: :delete %>
<% else %>
  <%= link_to 'Sign In', sign_in_path %>
  <%= link_to 'Sign Up', sign_up_path %>
<% end %>

<h2>Blocked Sources</h2>
<%= form_tag update_blocked_sources_path, method: :post do %>
  <% @sources.each do |source| %>
    <label>
      <%= check_box_tag "blocked_sources[]", source, current_user.source_blocked?(source) %>
      <%= source %>
    </label>
  <% end %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= submit_tag "Save" %>
<% end %>

<!-- COLUMNS -->
<div id="col-container">
  <div id="far-left-col">
    <h2 class="lean">Left</h2>
    <%= render_article_list(@theintercept_items, 'The Intercept') %>
    <%= render_article_list(@democracynow_items, 'Democracy Now!') %>
    <%= render_article_list(@dailybeast_items, 'Daily Beast') %>
    <%= render_article_list(@newyorker_items, 'The New Yorker') %>
  </div>

  <div id="left-col">
    <h2 class="lean">Center-Left</h2>
    <%= render_article_list(@nyt_items, 'New York Times') %>
    <%= render_article_list(@axios_items, 'Axios') %>
  </div>

  <div id="center-col">
    <h2 class="lean">Center</h2>
    <%= render_article_list(@thehill_items, 'The Hill') %>
    <%= render_article_list(@reuters_items, 'Reuters') %>
  </div>

  <div id="right-col">
    <h2 class="lean">Center-Right</h2>
    <%= render_article_list(@foxbusiness_items, 'Fox Business') %>
    <%= render_article_list(@thedispatch_items, 'The Dispatch') %>
  </div>

  <div id="far-right-col">
    <h2 class="lean">Right</h2>
    <%= render_article_list(@epochtimes_items, 'Epoch Times') %>
    <%= render_article_list(@dailymail_items, 'DailyMail') %>
    <%= render_article_list(@infowars_items, 'Infowars') %>
  </div>
</div>